# Generated by Django 4.2.6 on 2023-10-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecawheatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content_1',
            field=models.ImageField(null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='content_2',
            field=models.ImageField(null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='content_3',
            field=models.ImageField(null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='content_4',
            field=models.ImageField(null=True, upload_to='item_images/'),
        ),
    ]
