# Generated by Django 4.2.6 on 2023-10-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecawheatapp', '0002_item_content_1_item_content_2_item_content_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
