# Generated by Django 4.2.6 on 2023-10-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecawheatapp', '0003_item_description1_item_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
